#!/usr/bin/env node
// build-places.mjs — data/places.csv  →  src/data/places.ts
//
// Run once curation lands, then whenever the CSV changes:
//   node scripts/build-places.mjs
//
// Validates as it goes and REFUSES to write a broken file. Cheap insurance against
// a typo that only shows up as a blank map at 23:00.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'

const TAGS = ['running','hiking','swimming','live-music','food','coffee','markets','art','nightlife','outdoors','wellness','social']
const CITIES = ['cape-town','tokyo']
const SRC = 'data/places.csv'
const OUT = 'src/data/places.ts'

if (!existsSync(SRC)) { console.error(`✗ ${SRC} not found`); process.exit(1) }

// Minimal RFC4180 parser — handles quoted fields with commas.
function parseCSV(text) {
  const rows = []; let row = [], field = '', q = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (q) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++ }
      else if (c === '"') q = false
      else field += c
    } else if (c === '"') q = true
    else if (c === ',') { row.push(field); field = '' }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = '' }
    else if (c !== '\r') field += c
  }
  if (field || row.length) { row.push(field); rows.push(row) }
  return rows.filter((r) => r.some((c) => c.trim()))
}

const [header, ...body] = parseCSV(readFileSync(SRC, 'utf8'))
const cols = header.map((h) => h.trim())
const get = (r, name) => (r[cols.indexOf(name)] ?? '').trim()

const errors = []
const seen = new Set()
let happeningNow = 0

const places = body.map((r, i) => {
  const line = i + 2
  const id = get(r, 'id')
  const fail = (m) => errors.push(`line ${line} (${id || '?'}): ${m}`)

  if (!id) fail('missing id')
  if (seen.has(id)) fail('duplicate id')
  seen.add(id)

  const city = get(r, 'city')
  if (!CITIES.includes(city)) fail(`bad city "${city}"`)

  const lat = Number(get(r, 'lat')), lng = Number(get(r, 'lng'))
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) fail('lat/lng not numeric')
  if (city === 'cape-town' && (lat > -33 || lat < -35 || lng < 18 || lng > 19)) fail(`coords ${lat},${lng} are not in Cape Town — check you did not swap lat and lng`)
  if (city === 'tokyo' && (lat < 35 || lat > 36.5 || lng < 139 || lng > 140.5)) fail(`coords ${lat},${lng} are not in Tokyo`)

  const tags = get(r, 'tags').split('|').map((t) => t.trim()).filter(Boolean)
  if (!tags.length) fail('no tags — it can never be recommended')
  tags.forEach((t) => { if (!TAGS.includes(t)) fail(`tag "${t}" is not in the vocabulary`) })

  const kind = get(r, 'schedule_kind')
  let schedule
  if (kind === 'offset') {
    const m = Number(get(r, 'offset_minutes'))
    if (!Number.isFinite(m)) fail('offset_minutes missing')
    if (m >= 15 && m <= 30) happeningNow++
    schedule = { kind: 'offset', minutes: m }
  } else if (kind === 'clock') {
    schedule = {
      kind: 'clock',
      dayOffset: Number(get(r, 'day_offset') || 0),
      hour: Number(get(r, 'hour')),
      minute: Number(get(r, 'minute') || 0),
    }
    if (!Number.isFinite(schedule.hour)) fail('hour missing')
  } else fail(`schedule_kind must be offset or clock, got "${kind}"`)

  const image = get(r, 'image')
  if (!image.startsWith('/images/')) fail('image must be a local /images/… path, not a remote URL')
  if (!get(r, 'image_credit')) fail('image_credit missing (Unsplash licence condition)')

  const mLat = get(r, 'maps_lat'), mLng = get(r, 'maps_lng')

  return {
    id, city, area: get(r, 'area'), kind: get(r, 'kind') || 'event',
    title: get(r, 'title'), blurb: get(r, 'blurb'), lat, lng, schedule,
    durationMin: Number(get(r, 'duration_min') || 60),
    price: get(r, 'price') || null, tags, image,
    imageCredit: get(r, 'image_credit'),
    ...(mLat ? { mapsLat: Number(mLat) } : {}),
    ...(mLng ? { mapsLng: Number(mLng) } : {}),
    ...(get(r, 'source_url') ? { sourceUrl: get(r, 'source_url') } : {}),
  }
})

if (!happeningNow) errors.push('NO HAPPENING-NOW EVENT: at least one row needs schedule_kind=offset with offset_minutes between 15 and 30. The closing beat of the demo depends on it.')

if (errors.length) {
  console.error('✗ places.csv has problems — nothing written:\n' + errors.map((e) => '  · ' + e).join('\n'))
  process.exit(1)
}

const out = `// GENERATED by scripts/build-places.mjs — do not hand-edit.
// Source: data/places.csv  ·  ${places.length} places  ·  ${new Date().toISOString()}

import type { Place } from './types'

export const PLACES: Place[] = ${JSON.stringify(places, null, 2)}

export const placeById = (id: string): Place | undefined =>
  PLACES.find((p) => p.id === id)
`
writeFileSync(OUT, out)
console.log(`✓ ${places.length} places → ${OUT}`)
console.log(`  cape-town: ${places.filter((p) => p.city === 'cape-town').length} · tokyo: ${places.filter((p) => p.city === 'tokyo').length} · happening-now: ${happeningNow}`)
