// GENERATED by scripts/build-places.mjs — do not hand-edit.
// Source: data/places.csv · 58 places · 2026-09-19T07:51:02.957Z

import type { Place } from './types'

export const PLACES: Place[] = [
  {
    "id": "ct-cafe-chiffon",
    "city": "cape-town",
    "area": "Green Point",
    "kind": "place",
    "title": "Café Chiffon",
    "blurb": "Small café tucked into the Old Cape Quarter courtyard. Good for a slow morning that doesn't turn into a whole plan.",
    "address": "SHOP GF007, Old Cape Quarter, 72 Waterkant St, Green Point",
    "lat": -33.906,
    "lng": 18.41,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 8,
      "minute": 30
    },
    "durationMin": 60,
    "price": null,
    "tags": [
      "coffee",
      "food"
    ],
    "image": "/images/cafe-chiffon.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-truth-coffee",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "place",
    "title": "Truth Coffee Roasting",
    "blurb": "Roastery and café on Buitenkant, as known for the steampunk fit-out as the coffee. Busy from opening.",
    "address": "36 Buitenkant St, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 8,
      "minute": 0
    },
    "durationMin": 60,
    "price": null,
    "tags": [
      "coffee",
      "food"
    ],
    "image": "/images/truth-coffee.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-the-ladder",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "place",
    "title": "The Ladder",
    "blurb": "Bree Street spot for a long breakfast or a working hour with a flat white.",
    "address": "136 Bree St, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 60,
    "price": null,
    "tags": [
      "coffee",
      "food"
    ],
    "image": "/images/the-ladder.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-strangers-club",
    "city": "cape-town",
    "area": "Green Point",
    "kind": "place",
    "title": "The Strangers Club",
    "blurb": "Neighbourhood café and bar off Braemar. Quiet in the morning, considerably less so later.",
    "address": "1 Braemar Rd, Green Point",
    "lat": -33.906,
    "lng": 18.41,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "coffee",
      "food",
      "social"
    ],
    "image": "/images/strangers-club.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-hudsons",
    "city": "cape-town",
    "area": "Claremont",
    "kind": "place",
    "title": "Hudsons",
    "blurb": "Burgers and a room that stays loud. Go with people, not a book.",
    "address": "25 Protea Rd, Claremont",
    "lat": -33.983,
    "lng": 18.465,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 18,
      "minute": 30
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "food",
      "social"
    ],
    "image": "/images/hudsons.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-the-barn",
    "city": "cape-town",
    "area": "Rondebosch",
    "kind": "place",
    "title": "The Barn Restaurant",
    "blurb": "Rondebosch standby on Klipfontein. Unfussy, reliable, easy to get a table.",
    "address": "Klipfontein Rd, Rondebosch",
    "lat": -33.96,
    "lng": 18.475,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 18,
      "minute": 30
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "food"
    ],
    "image": "/images/the-barn.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-hussar-grill",
    "city": "cape-town",
    "area": "Mouille Point",
    "kind": "place",
    "title": "The Hussar Grill",
    "blurb": "Steak on Beach Road with the sea across the way. Book if it's a Friday.",
    "address": "New Cumberland Building, Beach Rd, Mouille Point",
    "lat": -33.899,
    "lng": 18.409,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "food"
    ],
    "image": "/images/hussar-grill.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-mulberry-prince",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "place",
    "title": "Mulberry & Prince",
    "blurb": "Pepper Street kitchen doing a short, changing menu. Small room, book ahead.",
    "address": "12 Pepper St, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "food"
    ],
    "image": "/images/mulberry-prince.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-happy-uncles",
    "city": "cape-town",
    "area": "Salt River",
    "kind": "place",
    "title": "The Happy Uncles",
    "blurb": "Halal fine dining on Voortrekker Road. A proper sit-down evening, ten minutes from Woodstock.",
    "address": "100 Voortrekker Rd, Salt River",
    "lat": -33.93,
    "lng": 18.465,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "food",
      "halal"
    ],
    "image": "/images/happy-uncles.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-cecilia-forest",
    "city": "cape-town",
    "area": "Wynberg",
    "kind": "event",
    "title": "Cecilia Forest climb",
    "blurb": "Pine forest switchbacks up the back of the mountain, with a waterfall if you carry on. Shaded most of the way.",
    "address": "Cecilia Forest Hiking Trail, Wynberg",
    "lat": -34.002,
    "lng": 18.467,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 7,
      "minute": 0
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "hiking",
      "outdoors"
    ],
    "image": "/images/cecilia-forest.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-silvermine",
    "city": "cape-town",
    "area": "Silvermine",
    "kind": "event",
    "title": "Silvermine reservoir walk",
    "blurb": "Flat loop around the reservoir with the whole peninsula on either side. Easy enough to talk the whole way.",
    "address": "Table Mountain National Park, Silvermine",
    "lat": -34.09,
    "lng": 18.41,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 8,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "hiking",
      "outdoors",
      "nature"
    ],
    "image": "/images/silvermine.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-kloof-corner",
    "city": "cape-town",
    "area": "Table Mountain",
    "kind": "event",
    "title": "Kloof Corner at golden hour",
    "blurb": "Forty-five minutes up, the best view in the city, and back down before dark. Bring a jacket.",
    "address": "Contour Path, Table Mountain",
    "lat": -33.962,
    "lng": 18.409,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 17,
      "minute": 30
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "hiking",
      "outdoors"
    ],
    "image": "/images/kloof-corner.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-newlands-forest",
    "city": "cape-town",
    "area": "Newlands",
    "kind": "event",
    "title": "Newlands Forest run",
    "blurb": "Trails under the pines with the contour path if you want more. Cool even when town is baking.",
    "address": "Table Mountain National Park, Newlands",
    "lat": -33.977,
    "lng": 18.453,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 7,
      "minute": 30
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "running",
      "hiking",
      "outdoors"
    ],
    "image": "/images/newlands-forest.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-mamma-mia",
    "city": "cape-town",
    "area": "Foreshore",
    "kind": "event",
    "title": "MAMMA MIA! at Artscape",
    "blurb": "The musical, full staging, at Artscape. The kind of night out you book for other people and then enjoy more than they do.",
    "address": "Artscape Theatre Centre, D.F. Malan St, Foreshore",
    "lat": -33.919,
    "lng": 18.431,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 30
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "live-shows",
      "theatre",
      "art"
    ],
    "image": "/images/mamma-mia.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-womad",
    "city": "cape-town",
    "area": "Foreshore",
    "kind": "event",
    "title": "WOMAD South Africa",
    "blurb": "World music across several stages at Artscape — heritage, collaboration, and a lot of people dancing badly.",
    "address": "Artscape Theatre Centre, D.F. Malan St, Foreshore",
    "lat": -33.919,
    "lng": 18.431,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 16,
      "minute": 0
    },
    "durationMin": 300,
    "price": null,
    "tags": [
      "live-shows",
      "music",
      "social",
      "heritage"
    ],
    "image": "/images/womad.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-extreme-festival",
    "city": "cape-town",
    "area": "Killarney Gardens",
    "kind": "event",
    "title": "Extreme Festival at Killarney",
    "blurb": "Motorsport day at Killarney. Loud, hot, and completely absorbing whether or not you know what you're watching.",
    "address": "6 Potsdam Rd, Table View",
    "lat": -33.826,
    "lng": 18.525,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 360,
    "price": null,
    "tags": [
      "social",
      "outdoors",
      "motorsport"
    ],
    "image": "/images/extreme-festival.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-clay-cafe-hout-bay",
    "city": "cape-town",
    "area": "Hout Bay",
    "kind": "place",
    "title": "Clay Café Hout Bay",
    "blurb": "Pick a piece, paint it, they fire it and you collect it later. Two hours disappear.",
    "address": "4080 Hout Bay Main Rd, Hout Bay",
    "lat": -34.038,
    "lng": 18.354,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "making",
      "pottery",
      "family"
    ],
    "image": "/images/clay-cafe-hout-bay.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-city-rock",
    "city": "cape-town",
    "area": "Paarden Eiland",
    "kind": "place",
    "title": "City Rock",
    "blurb": "Indoor climbing in Paarden Eiland. Walls for people who've never done it and walls for people who have.",
    "address": "9 Milner St, Paarden Eiland",
    "lat": -33.906,
    "lng": 18.475,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 17,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "fashion",
      "climbing",
      "social"
    ],
    "image": "/images/city-rock.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-rush-claremont",
    "city": "cape-town",
    "area": "Claremont",
    "kind": "place",
    "title": "Rush Extreme",
    "blurb": "Trampolines, foam pits, and a heart rate you weren't expecting. Better with a group.",
    "address": "25 Stegman Rd, Claremont",
    "lat": -33.983,
    "lng": 18.465,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 16,
      "minute": 0
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "fashion",
      "social",
      "family"
    ],
    "image": "/images/rush.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-kayak-adventures",
    "city": "cape-town",
    "area": "V&A Waterfront",
    "kind": "event",
    "title": "Sunrise kayak from Battery Park",
    "blurb": "Out past the harbour wall at first light. Seals most mornings, whales if you're lucky.",
    "address": "Battery Park, Dock Rd, V&A Waterfront",
    "lat": -33.904,
    "lng": 18.42,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 6,
      "minute": 30
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "outdoors",
      "paddling",
      "nature"
    ],
    "image": "/images/kayak-adventures.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-acrobranch",
    "city": "cape-town",
    "area": "Hout Bay",
    "kind": "place",
    "title": "Acrobranch Hout Bay",
    "blurb": "Rope courses through the trees at increasing heights. You will find out quite quickly how you feel about heights.",
    "address": "1 Hout Bay Main Rd, Hout Bay",
    "lat": -34.038,
    "lng": 18.354,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "outdoors",
      "fashion",
      "family"
    ],
    "image": "/images/acrobranch.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-paragliding",
    "city": "cape-town",
    "area": "Signal Hill",
    "kind": "event",
    "title": "Tandem paraglide off Signal Hill",
    "blurb": "Run off the side of Signal Hill strapped to someone who's done it a thousand times. Landing is on the Sea Point side.",
    "address": "2 Signal Hill Rd, Signal Hill",
    "lat": -33.915,
    "lng": 18.403,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 16,
      "minute": 0
    },
    "durationMin": 60,
    "price": null,
    "tags": [
      "outdoors"
    ],
    "image": "/images/paragliding.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-chefs-studio",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "event",
    "title": "Evening class at The Chefs Studio",
    "blurb": "Bree Street kitchen, a small class, and something you can actually cook again on a Tuesday.",
    "address": "103 Bree St, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 18,
      "minute": 0
    },
    "durationMin": 180,
    "price": null,
    "tags": [
      "making",
      "cooking",
      "food",
      "social"
    ],
    "image": "/images/chefs-studio.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-faeezas-kitchen",
    "city": "cape-town",
    "area": "Bo-Kaap",
    "kind": "event",
    "title": "Cooking with Faeeza",
    "blurb": "Home kitchen in the Bo-Kaap. You cook, you eat what you cooked, and you leave with the recipes.",
    "address": "Chiappini Ln, Schotsche Kloof",
    "lat": -33.92,
    "lng": 18.413,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 11,
      "minute": 0
    },
    "durationMin": 180,
    "price": null,
    "tags": [
      "making",
      "cooking",
      "food",
      "halal",
      "heritage"
    ],
    "image": "/images/faeezas-kitchen.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-bokaap-cooking-tour",
    "city": "cape-town",
    "area": "Bo-Kaap",
    "kind": "event",
    "title": "Bo-Kaap cooking tour",
    "blurb": "Walk the neighbourhood, then cook in it. Half history lesson, half lunch.",
    "address": "46 Rose St, Schotsche Kloof",
    "lat": -33.92,
    "lng": 18.413,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 240,
    "price": null,
    "tags": [
      "making",
      "cooking",
      "heritage",
      "food"
    ],
    "image": "/images/bokaap-cooking-tour.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-clay-hands",
    "city": "cape-town",
    "area": "Woodstock",
    "kind": "event",
    "title": "Wheel throwing at Clay Hands",
    "blurb": "Two hours at the wheel on Victoria Road. You will make something wonky and you will keep it.",
    "address": "196 Victoria Rd, Woodstock",
    "lat": -33.927,
    "lng": 18.447,
    "schedule": {
      "kind": "offset",
      "minutes": 22
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "making",
      "pottery"
    ],
    "image": "/images/clay-hands.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-sasha-leon",
    "city": "cape-town",
    "area": "Gardens",
    "kind": "event",
    "title": "Make a ring in a day",
    "blurb": "Silversmithing in a Gardens studio — cut, solder, file, polish, wear it home.",
    "address": "4 Wembley Rd, Gardens",
    "lat": -33.931,
    "lng": 18.411,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 9,
      "minute": 30
    },
    "durationMin": 300,
    "price": null,
    "tags": [
      "making"
    ],
    "image": "/images/sasha-leon.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-clay-cafe-century-city",
    "city": "cape-town",
    "area": "Century City",
    "kind": "place",
    "title": "Clay Café Century City",
    "blurb": "Same idea as Hout Bay, closer to town, and indoors when the wind is up.",
    "address": "37 Bridgeway, Century City",
    "lat": -33.893,
    "lng": 18.51,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "making",
      "pottery",
      "family"
    ],
    "image": "/images/clay-cafe-century-city.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-zeitz-mocaa",
    "city": "cape-town",
    "area": "V&A Waterfront",
    "kind": "place",
    "title": "Zeitz MOCAA",
    "blurb": "Contemporary African art inside a converted grain silo. Worth it for the atrium alone.",
    "address": "S Arm Rd, V&A Waterfront",
    "lat": -33.904,
    "lng": 18.42,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "art"
    ],
    "image": "/images/zeitz-mocaa.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-artscape",
    "city": "cape-town",
    "area": "Foreshore",
    "kind": "place",
    "title": "Artscape Theatre Centre",
    "blurb": "The city's main stage. Whatever's on this week, it's on here.",
    "address": "D.F. Malan St, Foreshore",
    "lat": -33.919,
    "lng": 18.431,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 30
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "art",
      "live-shows",
      "theatre"
    ],
    "image": "/images/artscape.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-safra-gala",
    "city": "cape-town",
    "area": "Parow",
    "kind": "event",
    "title": "SAFRA Heritage Gala",
    "blurb": "An evening of heritage performance in Parow. Dress for it.",
    "address": "20 Picton St, Parow",
    "lat": -33.901,
    "lng": 18.595,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 18,
      "minute": 0
    },
    "durationMin": 210,
    "price": null,
    "tags": [
      "live-shows",
      "heritage",
      "social"
    ],
    "image": "/images/safra-gala.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-cape-ballet",
    "city": "cape-town",
    "area": "Gardens",
    "kind": "event",
    "title": "Cape Ballet Africa",
    "blurb": "Contemporary ballet from a young company. Shorter than you expect and much better.",
    "address": "2 Hof St, Gardens",
    "lat": -33.931,
    "lng": 18.411,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "art",
      "live-shows",
      "theatre"
    ],
    "image": "/images/cape-ballet.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-create-sewing",
    "city": "cape-town",
    "area": "Observatory",
    "kind": "event",
    "title": "Sewing studio evening",
    "blurb": "Lower Main Road studio with machines, patterns and someone to stop you ruining the fabric.",
    "address": "142 Lower Main Rd, Observatory",
    "lat": -33.939,
    "lng": 18.469,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 18,
      "minute": 0
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "making",
      "fashion"
    ],
    "image": "/images/create-sewing.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-yolo-fiesta",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "event",
    "title": "YOLO Fiesta",
    "blurb": "Long Street, loud, late. Go if that's the evening you're after.",
    "address": "38 Long St, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 21,
      "minute": 0
    },
    "durationMin": 240,
    "price": null,
    "tags": [
      "social",
      "music"
    ],
    "image": "/images/yolo-fiesta.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-fashion-week",
    "city": "cape-town",
    "area": "Kenilworth",
    "kind": "event",
    "title": "Cape Town Fashion Week",
    "blurb": "Runway shows at Kenilworth Racecourse. Half the interest is the crowd outside.",
    "address": "Hollywoodbets Kenilworth Racecourse, 105 Rosmead Ave, Kenilworth",
    "lat": -33.995,
    "lng": 18.477,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 17,
      "minute": 0
    },
    "durationMin": 240,
    "price": null,
    "tags": [
      "fashion",
      "art",
      "social"
    ],
    "image": "/images/fashion-week.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-nantes-race",
    "city": "cape-town",
    "area": "Athlone",
    "kind": "event",
    "title": "Nantes Heritage Race",
    "blurb": "Road race through Athlone with a community behind it. Entry on the day.",
    "address": "Cross Blvd, Athlone",
    "lat": -33.964,
    "lng": 18.51,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 6,
      "minute": 30
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "running",
      "heritage",
      "social"
    ],
    "image": "/images/nantes-race.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-sanlam-marathon",
    "city": "cape-town",
    "area": "Green Point",
    "kind": "event",
    "title": "Sanlam Cape Town Marathon",
    "blurb": "The big one. Green Point start, the whole city out on the pavement.",
    "address": "Fritz Sonnenberg Rd, Green Point",
    "lat": -33.906,
    "lng": 18.41,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 6,
      "minute": 0
    },
    "durationMin": 300,
    "price": null,
    "tags": [
      "running"
    ],
    "image": "/images/sanlam-marathon.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-run-promenade",
    "city": "cape-town",
    "area": "Green Point",
    "kind": "event",
    "title": "Run the promenade",
    "blurb": "Flat, lit, and busy with other runners. The easiest 5k in the city to commit to.",
    "address": "100 Beach Rd, Green Point",
    "lat": -33.906,
    "lng": 18.41,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 18,
      "minute": 0
    },
    "durationMin": 60,
    "price": "Free",
    "tags": [
      "running",
      "outdoors",
      "social"
    ],
    "image": "/images/run-promenade.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-ladles-of-love",
    "city": "cape-town",
    "area": "Epping",
    "kind": "event",
    "title": "Ladles of Love packing shift",
    "blurb": "Two hours on the line in Epping packing meals. Go with someone; the time passes faster.",
    "address": "Unit 4, Hewett Park, 17 Hewett Ave, Epping",
    "lat": -33.935,
    "lng": 18.545,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 120,
    "price": "Free",
    "tags": [
      "giving-back",
      "social"
    ],
    "image": "/images/ladles-of-love.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-islamic-relief",
    "city": "cape-town",
    "area": "Lansdowne",
    "kind": "event",
    "title": "Islamic Relief volunteer morning",
    "blurb": "Sorting and distribution from the Lansdowne office. Show up, they'll find you a job.",
    "address": "396 Imam Haron Rd, Lansdowne",
    "lat": -33.988,
    "lng": 18.503,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 180,
    "price": "Free",
    "tags": [
      "giving-back",
      "social"
    ],
    "image": "/images/islamic-relief.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-gift-of-the-givers",
    "city": "cape-town",
    "area": "Belthorn Estate",
    "kind": "event",
    "title": "Gift of the Givers packing",
    "blurb": "Disaster-response packing in Belthorn. Unglamorous and completely worth the morning.",
    "address": "4 Arbeids Rd, Belthorn Estate",
    "lat": -33.992,
    "lng": 18.515,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 180,
    "price": "Free",
    "tags": [
      "giving-back",
      "social"
    ],
    "image": "/images/gift-of-the-givers.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-sanccob",
    "city": "cape-town",
    "area": "Table View",
    "kind": "place",
    "title": "SANCCOB seabird centre",
    "blurb": "Penguin and seabird rehabilitation in Table View. You can visit, and you can help.",
    "address": "22 Pentz Dr, Table View",
    "lat": -33.82,
    "lng": 18.49,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "giving-back",
      "nature",
      "family"
    ],
    "image": "/images/sanccob.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-two-oceans-aquarium",
    "city": "cape-town",
    "area": "V&A Waterfront",
    "kind": "place",
    "title": "Two Oceans Aquarium",
    "blurb": "Where two oceans meet, indoors, with a kelp forest tank you'll stand in front of for longer than planned.",
    "address": "Dock Rd, V&A Waterfront",
    "lat": -33.904,
    "lng": 18.42,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "social",
      "nature",
      "family"
    ],
    "image": "/images/two-oceans.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-trash-bash",
    "city": "cape-town",
    "area": "Muizenberg",
    "kind": "event",
    "title": "Trash Bash beach clean",
    "blurb": "An hour on Sunrise Beach with bags and gloves, followed by coffee. Genuinely satisfying.",
    "address": "Sunrise Beach, Muizenberg",
    "lat": -34.103,
    "lng": 18.47,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 8,
      "minute": 0
    },
    "durationMin": 90,
    "price": "Free",
    "tags": [
      "giving-back",
      "outdoors",
      "beach",
      "social"
    ],
    "image": "/images/trash-bash.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-greenpop",
    "city": "cape-town",
    "area": "Woodstock",
    "kind": "event",
    "title": "Greenpop planting day",
    "blurb": "Tree planting run out of the Mountain Road hub in Woodstock. Dirt under the fingernails, four blocks from here.",
    "address": "107 Mountain Rd, Woodstock",
    "lat": -33.927,
    "lng": 18.447,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 240,
    "price": null,
    "tags": [
      "giving-back",
      "outdoors",
      "nature"
    ],
    "image": "/images/greenpop.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-grotto-spa",
    "city": "cape-town",
    "area": "Gardens",
    "kind": "place",
    "title": "The Grotto Spa",
    "blurb": "Hydrotherapy and quiet up at Greys Pass. Go in wound up, come out useless.",
    "address": "Greys Pass, Gardens",
    "lat": -33.931,
    "lng": 18.411,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 10,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "wellness"
    ],
    "image": "/images/grotto-spa.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-seasonal-reset",
    "city": "cape-town",
    "area": "Zonnebloem",
    "kind": "event",
    "title": "The Seasonal Reset",
    "blurb": "An afternoon at Nova Core to stop and take stock. More practical than it sounds.",
    "address": "Nova Core, 47 De Villiers St, Zonnebloem",
    "lat": -33.932,
    "lng": 18.429,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 14,
      "minute": 0
    },
    "durationMin": 180,
    "price": null,
    "tags": [
      "wellness",
      "social"
    ],
    "image": "/images/seasonal-reset.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-flow-lab",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "event",
    "title": "Flow Lab Friday",
    "blurb": "Breathwork and movement on Loop Street to close out the week. Ninety minutes, no experience needed.",
    "address": "Habitus Wellness, 61 Loop St, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 17,
      "minute": 30
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "wellness",
      "fashion"
    ],
    "image": "/images/flow-lab.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-lifestyle-padel",
    "city": "cape-town",
    "area": "Claremont",
    "kind": "event",
    "title": "Padel at Stadium on Main",
    "blurb": "Easiest racket sport to pick up and the hardest to stop playing. Courts book out after five.",
    "address": "Mezzanine level, Stadium on Main, 99 Main Rd, Claremont",
    "lat": -33.983,
    "lng": 18.465,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 18,
      "minute": 0
    },
    "durationMin": 90,
    "price": null,
    "tags": [
      "fashion",
      "social"
    ],
    "image": "/images/lifestyle-padel.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-garys-surf-school",
    "city": "cape-town",
    "area": "Muizenberg",
    "kind": "event",
    "title": "Learn to surf at Muizenberg",
    "blurb": "Gary's has been putting beginners on boards at Surfers Corner for decades. Wetsuit included.",
    "address": "Balmoral Building, 34 Beach Rd, Muizenberg",
    "lat": -34.103,
    "lng": 18.47,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "fashion",
      "outdoors",
      "surfing",
      "beach"
    ],
    "image": "/images/garys-surf.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-cycle-tour",
    "city": "cape-town",
    "area": "Rondebosch",
    "kind": "event",
    "title": "Cape Town Cycle Tour",
    "blurb": "109km around the peninsula with thirty thousand other people. Train for it or suffer beautifully.",
    "address": "65 Ave De Mist, Rondebosch",
    "lat": -33.96,
    "lng": 18.475,
    "schedule": {
      "kind": "clock",
      "dayOffset": 1,
      "hour": 6,
      "minute": 0
    },
    "durationMin": 360,
    "price": null,
    "tags": [
      "fashion",
      "outdoors",
      "cycling"
    ],
    "image": "/images/cycle-tour.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-story-jam",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "event",
    "title": "Story Jam",
    "blurb": "True stories told live on Loop Street by people who are not performers. Consistently the best night out in town.",
    "address": "35 Loop St, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 30
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "live-shows",
      "social"
    ],
    "image": "/images/story-jam.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-first-thursdays",
    "city": "cape-town",
    "area": "City Bowl",
    "kind": "event",
    "title": "First Thursdays",
    "blurb": "Galleries and shops stay open late and the whole city centre walks around. Start on Church Street.",
    "address": "1 Orphan Ln, Cape Town City Centre",
    "lat": -33.925,
    "lng": 18.418,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 17,
      "minute": 0
    },
    "durationMin": 300,
    "price": "Free",
    "tags": [
      "art",
      "social"
    ],
    "image": "/images/first-thursdays.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "ct-obz-quiz-night",
    "city": "cape-town",
    "area": "Observatory",
    "kind": "event",
    "title": "Quiz night in Obz",
    "blurb": "Lower Main Road, teams of four, and one round you will argue about afterwards.",
    "address": "Shop 5, 170 Lower Main Rd, Observatory",
    "lat": -33.939,
    "lng": 18.469,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 19,
      "minute": 30
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "social"
    ],
    "image": "/images/obz-quiz.jpg",
    "imageCredit": "TODO"
  },
  {
    "id": "tk-placeholder-coffee",
    "city": "tokyo",
    "area": "Nakameguro",
    "kind": "place",
    "title": "PLACEHOLDER — Nakameguro coffee",
    "blurb": "Placeholder row. Real Tokyo curation is being collected; replace this whole block before the run-through.",
    "address": "PLACEHOLDER, Nakameguro, Meguro City",
    "lat": 35.644,
    "lng": 139.699,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 9,
      "minute": 0
    },
    "durationMin": 60,
    "price": null,
    "tags": [
      "coffee",
      "food"
    ],
    "image": "/images/tokyo-placeholder-1.jpg",
    "imageCredit": "PLACEHOLDER"
  },
  {
    "id": "tk-placeholder-making",
    "city": "tokyo",
    "area": "Yanaka",
    "kind": "place",
    "title": "PLACEHOLDER — Yanaka pottery studio",
    "blurb": "Placeholder row. Real Tokyo curation is being collected; replace this whole block before the run-through.",
    "address": "PLACEHOLDER, Yanaka, Taito City",
    "lat": 35.718,
    "lng": 139.73,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 11,
      "minute": 0
    },
    "durationMin": 120,
    "price": null,
    "tags": [
      "making",
      "pottery"
    ],
    "image": "/images/tokyo-placeholder-2.jpg",
    "imageCredit": "PLACEHOLDER"
  },
  {
    "id": "tk-placeholder-running",
    "city": "tokyo",
    "area": "Shibuya",
    "kind": "event",
    "title": "PLACEHOLDER — Imperial Palace loop run",
    "blurb": "Placeholder row. Real Tokyo curation is being collected; replace this whole block before the run-through.",
    "address": "PLACEHOLDER, Shibuya City",
    "lat": 35.658,
    "lng": 139.701,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 18,
      "minute": 30
    },
    "durationMin": 60,
    "price": "Free",
    "tags": [
      "running",
      "outdoors",
      "social"
    ],
    "image": "/images/tokyo-placeholder-3.jpg",
    "imageCredit": "PLACEHOLDER"
  },
  {
    "id": "tk-placeholder-shows",
    "city": "tokyo",
    "area": "Shimokitazawa",
    "kind": "event",
    "title": "PLACEHOLDER — Shimokitazawa live house",
    "blurb": "Placeholder row. Real Tokyo curation is being collected; replace this whole block before the run-through.",
    "address": "PLACEHOLDER, Shimokitazawa, Setagaya City",
    "lat": 35.661,
    "lng": 139.668,
    "schedule": {
      "kind": "clock",
      "dayOffset": 0,
      "hour": 20,
      "minute": 0
    },
    "durationMin": 150,
    "price": null,
    "tags": [
      "live-shows",
      "music",
      "social"
    ],
    "image": "/images/tokyo-placeholder-4.jpg",
    "imageCredit": "PLACEHOLDER"
  }
]

export const placeById = (id: string): Place | undefined =>
  PLACES.find((p) => p.id === id)
